version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=dev_emerchantpay
      - POSTGRES_USER=dev_db_admin
      - POSTGRES_PASSWORD=dev_db_password
    ports:
      - "5450:5432"
    networks:
      - emerchantpay_network
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./config/db-init/:/docker-entrypoint-initdb.d/

  keycloak:
    image: quay.io/keycloak/keycloak:22.0.1
    command: start-dev --import-realm
    environment:
      - KEYCLOAK_ADMIN=dev_kc_admin
      - KEYCLOAK_ADMIN_PASSWORD=dev_kc_password
      - KC_DB=postgres
      - KC_DB_URL_HOST=db
      - KC_DB_URL_PORT=5432
      - KC_DB_URL_DATABASE=dev_emerchantpay
      - KC_DB_USERNAME=dev_db_admin
      - KC_DB_PASSWORD=dev_db_password
      - KC_DB_SCHEMA=keycloak
      - KC_HEALTH_ENABLED=true
      - KC_METRICS_ENABLED=true
    ports:
      - "5451:8080"
    volumes:
      - ./config/keycloak-emerchantpay-realm.json:/opt/keycloak/data/import/keycloak-emerchantpay-realm.json
    networks:
      - emerchantpay_network
    depends_on:
      - db

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - emerchantpay_network

  kafka:
    image: confluentinc/cp-kafka:latest
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: LISTENER_DOCKER_INTERNAL://kafka:9092,LISTENER_DOCKER_EXTERNAL://localhost:9094
      KAFKA_LISTENER_DOCKER_INTERNAL: 0.0.0.0:9092
      KAFKA_LISTENER_DOCKER_EXTERNAL: 0.0.0.0:9094
      KAFKA_LISTENERS: LISTENER_DOCKER_INTERNAL://0.0.0.0:9092,LISTENER_DOCKER_EXTERNAL://0.0.0.0:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_DOCKER_INTERNAL:PLAINTEXT,LISTENER_DOCKER_EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_DOCKER_INTERNAL
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    volumes:
      - /var/lib/kafka/data
    ports:
      - "5452:9094"
    networks:
      - emerchantpay_network
    depends_on:
      - zookeeper

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    ports:
      - "5453:8080"
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9092
    networks:
      - emerchantpay_network
    depends_on:
      - kafka

volumes:
  postgres_data:

networks:
  emerchantpay_network:
    driver: bridge