version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=dev_emerchantpay
      - POSTGRES_USER=dev_admin
      - POSTGRES_PASSWORD=dev_password
    ports:
      - "5450:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: