spring:
  datasource:
    url: jdbc:postgresql://localhost:5450/dev_emerchantpay
    username: dev_db_admin
    password: dev_db_password
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        default_schema: transaction
  flyway:
    schemas: transaction
  security:
    cors:
      allowed-origins: http://localhost:8080
      allowed-methods: GET,POST,PUT,DELETE,OPTIONS
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:5451/realms/emerchantpay/protocol/openid-connect/certs
          #issuer-uri: http://localhost:5451/realms/emerchantpay/.well-known/openid-configuration
  kafka:
    bootstrap-servers: localhost:5452
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      group-id: transaction_microservice
      auto-offset-reset: earliest
      properties:
        spring:
          json:
            use.type.headers: false
            value:
              default:
                type: com.vvkozlov.emerchantpay.transaction.service.model.messagebroker.MerchantMbModel
            trusted:
              packages: '*'
springdoc:
  swagger-ui:
    path: /sw.html
    docExpansion: list
    deepLinking: true
webclient:
  merchant:
    connect-timeout: 2000
    read-timeout: 2000
    base-url: http://localhost:8081
server:
  port: 8082
logging:
  level:
#    root: DEBUG
    root: ERROR
    org.springframework.kafka: ERROR
#    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG
